name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Xcode
      run: sudo xcode-select -switch /Applications/Xcode_14.0.app && /usr/bin/xcodebuild -version

    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        pod setup

    - name: Build and Test
      run: xcodebuild test -workspace OldNorseDictionary.xcworkspace -scheme OldNorseDictionaryTests -destination 'platform=iOS Simulator,name=iPhone 14'

