name: Run Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:      

jobs:
  test:
     runs-on: macos-13

     steps:
     - uses: actions/checkout@v2

     - name: Set up Xcode
       run: sudo xcode-select -switch /Applications/Xcode.app && /usr/bin/xcodebuild -version

     - name: Build and Test
       run: xcodebuild test -scheme OldNorseDictionary -project OldNorseDictionary.xcodeproj CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO
